#!/usr/bin/env bash

# we need to set the permissions here because docker mounts volumes as root

chown -R couchdb:couchdb /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb

chmod -R 0770 /usr/local/var/lib/couchdb \
  /usr/local/var/log/couchdb \
  /usr/local/var/run/couchdb \
  /usr/local/etc/couchdb

chmod 664 /usr/local/etc/couchdb/*.ini
chmod 775 /usr/local/etc/couchdb/*.d

# Start at the same time logrotate, couchdb and nginx
(while true; do /usr/sbin/logrotate -v /etc/logrotate.conf; sleep 1d; done) & \
sudo -i -u couchdb mon couchdb > /dev/null 2>&1 & \
/usr/sbin/nginx > /dev/null 2>&1 & \
sleep infinity
